//! Deterministic dealing: [`deal`] builds the initial [`GameState`] from a
//! [`Seed`].
//!
//! This reproduces the original Windows Solitaire's deal exactly: the same
//! seed lays out the same board it does. The complete documented procedure —
//! part of the determinism contract and locked forever by the committed
//! fixtures under `tests/fixtures/` (independently generated by
//! `tests/fixtures/generate.py`):
//!
//! 1. **Initial deck order:** the 52 cards in deck-index order, ace to king
//!    with the suits interleaved clubs, diamonds, hearts, spades — see
//!    [`Card::from_index`].
//! 2. **Shuffle:** five passes of the naive swap shuffle over the C runtime
//!    generator of [`crate::rng`] seeded from the [`Seed`]: five times over,
//!    for `i` from 0 up to 51, draw `j = rand() % 52` and swap positions `i`
//!    and `j`. This is not Fisher–Yates and it is deliberately not corrected
//!    to be: 260 random transpositions mix the deck far past uniformity, and
//!    matching the original means matching it swap for swap.
//! 3. **Layout:** for round `r` in `0..7`, for pile `p` in `r..7`, take the
//!    next card off the **back** of the shuffled deck onto tableau `p` —
//!    face-up when `p == r` (each pile's last, top card), face-down
//!    otherwise. Tableau `p` ends up with `p` face-down cards under one
//!    face-up card. Dealing from the back is what the original does: its
//!    piles are stacks whose top is the last element.
//! 4. **Stock:** the 24 cards left at the front of the deck, still in shuffle
//!    order; the last of them (deck index 23) is the first card a draw turns
//!    onto the waste. The waste and all four foundations start empty.
//!
//! The card arrangement depends **only** on the seed. The [`GameConfig`]
//! parameterizes rules and the initial score (the Vegas buy-in) but never
//! card positions.

use crate::card::Card;
use crate::config::{GameConfig, ScoringMode};
use crate::pile::TABLEAU_COUNT;
use crate::rng::MsRand;
use crate::score::VEGAS_BUY_IN;
use crate::seed::Seed;
use crate::state::{GameState, TableauPile};

/// Cards in a deck.
const DECK_SIZE: u16 = 52;

/// How many times the shuffle sweeps the whole deck.
const SHUFFLE_PASSES: u8 = 5;

/// Cards the layout deals onto the tableau: 1 + 2 + ... + 7.
const TABLEAU_CARDS: usize = 28;

/// Deals the initial state of a game from a seed.
///
/// Same seed, same deal — on every platform, forever. See the module
/// documentation for the exact procedure.
///
/// ```
/// use sol_engine::{DrawMode, GameConfig, ScoringMode, Seed, deal};
///
/// let config = GameConfig {
///     draw_mode: DrawMode::Three,
///     scoring: ScoringMode::Standard,
///     timed: false,
/// };
/// let state = deal(Seed::new(42).unwrap(), config);
/// assert_eq!(state.stock().len(), 24);
/// assert_eq!(deal(Seed::new(42).unwrap(), config), state);
/// ```
#[must_use]
pub fn deal(seed: Seed, config: GameConfig) -> GameState {
    let mut deck = shuffled_deck(seed);
    // The deck is a stack whose top is its last card, so the 28 cards the
    // tableau takes come off the back, topmost first. What is left in `deck`
    // is the stock, already bottom-to-top.
    let dealt = deck.split_off(deck.len().saturating_sub(TABLEAU_CARDS));
    let mut tableaus: [TableauPile; TABLEAU_COUNT as usize] = Default::default();
    let mut cards = dealt.into_iter().rev();
    for round in 0..usize::from(TABLEAU_COUNT) {
        // Round r deals one card to each of the piles r..7, in order; the
        // first of them lands on pile r as its final, face-up card.
        for (offset, (pile, card)) in tableaus
            .iter_mut()
            .skip(round)
            .zip(cards.by_ref())
            .enumerate()
        {
            if offset == 0 {
                pile.face_up.push(card);
            } else {
                pile.face_down.push(card);
            }
        }
    }
    // The 24 undealt cards, still bottom-to-top: the last element is the top
    // of the stock and the first card a draw turns over.
    let stock: Vec<Card> = deck;
    let initial_score = match config.scoring {
        ScoringMode::Vegas => VEGAS_BUY_IN,
        ScoringMode::Standard | ScoringMode::None => 0,
    };
    GameState {
        config,
        stock,
        waste: Vec::new(),
        foundations: Default::default(),
        tableaus,
        score: initial_score,
        elapsed_secs: 0,
        passes_completed: 0,
        won: false,
    }
}

/// The documented five-pass swap shuffle of the documented initial deck.
fn shuffled_deck(seed: Seed) -> Vec<Card> {
    let mut deck = initial_deck();
    let mut rng = MsRand::new(seed.get());
    for _ in 0..SHUFFLE_PASSES {
        for i in 0..DECK_SIZE {
            let j = rng.next() % DECK_SIZE;
            deck.swap(usize::from(i), usize::from(j));
        }
    }
    deck
}

/// The 52-card deck in the documented initial order.
fn initial_deck() -> Vec<Card> {
    // Infallible: DECK_SIZE is 52, so every index fits a u8.
    (0..DECK_SIZE)
        .map(|index| Card::from_index(u8::try_from(index).unwrap_or(0)))
        .collect()
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use std::collections::BTreeSet;

    use super::*;
    use crate::config::DrawMode;

    fn config(scoring: ScoringMode) -> GameConfig {
        GameConfig {
            draw_mode: DrawMode::Three,
            scoring,
            timed: false,
        }
    }

    fn dealt(seed: u16) -> GameState {
        deal(Seed::new(seed).unwrap(), config(ScoringMode::Standard))
    }

    #[test]
    fn initial_deck_is_documented_order() {
        let deck = initial_deck();
        assert_eq!(deck.len(), 52);
        assert_eq!(deck.first().unwrap().to_string(), "C1");
        assert_eq!(deck.get(1).unwrap().to_string(), "D1");
        assert_eq!(deck.get(2).unwrap().to_string(), "H1");
        assert_eq!(deck.get(3).unwrap().to_string(), "S1");
        assert_eq!(deck.get(4).unwrap().to_string(), "C2");
        assert_eq!(deck.last().unwrap().to_string(), "S13");
    }

    /// The shuffle is the original's, so a seed's deal is checkable against
    /// the 1996 binary's. Seed 1's board, top card of each tableau pile last.
    #[test]
    fn seed_one_deals_the_original_board() {
        let state = dealt(1);
        let rendered: Vec<String> = state
            .tableaus()
            .map(|pile| {
                pile.face_down()
                    .iter()
                    .chain(pile.face_up())
                    .map(ToString::to_string)
                    .collect::<Vec<_>>()
                    .join(",")
            })
            .collect();
        assert_eq!(
            rendered,
            [
                "D5",
                "H7,S6",
                "D9,D12,D10",
                "H6,S5,C1,D1",
                "D13,C11,H2,D3,D7",
                "S2,C7,S3,H13,S13,D4",
                "D8,S4,S7,C13,C5,H3,H12",
            ]
        );
        let stock: Vec<String> = state
            .stock()
            .iter()
            .rev()
            .map(ToString::to_string)
            .collect();
        assert_eq!(stock.first().unwrap(), "S12", "first card a draw turns");
        assert_eq!(stock.last().unwrap(), "S1", "last card of the stock");
    }

    #[test]
    fn every_card_dealt_exactly_once() {
        let state = dealt(1);
        let mut seen = BTreeSet::new();
        let mut total = 0_usize;
        for pile in state.tableaus() {
            for card in pile.face_down().iter().chain(pile.face_up()) {
                seen.insert(card.to_string());
                total += 1;
            }
        }
        for card in state.stock() {
            seen.insert(card.to_string());
            total += 1;
        }
        assert_eq!(total, 52);
        assert_eq!(seen.len(), 52, "no duplicates anywhere");
    }

    #[test]
    fn tableau_p_has_p_face_down_cards_and_one_face_up() {
        let state = dealt(42);
        for (index, pile) in state.tableaus().enumerate() {
            assert_eq!(pile.face_down().len(), index, "tableau {index} face-down");
            assert_eq!(pile.face_up().len(), 1, "tableau {index} face-up");
        }
    }

    #[test]
    fn stock_holds_24_waste_and_foundations_start_empty() {
        let state = dealt(0);
        assert_eq!(state.stock().len(), 24);
        assert!(state.waste().is_empty());
        assert!(state.foundations().all(<[Card]>::is_empty));
        assert_eq!(state.foundation_card_count(), 0);
    }

    #[test]
    fn fresh_game_meta_is_zeroed_and_not_won() {
        let state = dealt(7);
        assert_eq!(state.score(), 0);
        assert_eq!(state.elapsed_secs(), 0);
        assert_eq!(state.passes_completed(), 0);
        assert!(!state.is_won());
    }

    #[test]
    fn vegas_deal_charges_the_buy_in() {
        let state = deal(Seed::new(7).unwrap(), config(ScoringMode::Vegas));
        assert_eq!(state.score(), -52);
        let none = deal(Seed::new(7).unwrap(), config(ScoringMode::None));
        assert_eq!(none.score(), 0);
    }

    #[test]
    fn same_seed_deals_identically_different_seeds_differ() {
        assert_eq!(dealt(123), dealt(123));
        assert_ne!(dealt(0), dealt(1));
    }

    #[test]
    fn config_never_affects_the_card_arrangement() {
        let standard = deal(
            Seed::new(9).unwrap(),
            GameConfig {
                draw_mode: DrawMode::One,
                scoring: ScoringMode::Standard,
                timed: true,
            },
        );
        let vegas = deal(
            Seed::new(9).unwrap(),
            GameConfig {
                draw_mode: DrawMode::Three,
                scoring: ScoringMode::Vegas,
                timed: false,
            },
        );
        assert_eq!(standard.stock(), vegas.stock());
        let same_tableaus = standard.tableaus().eq(vegas.tableaus());
        assert!(same_tableaus);
    }
}
