//! The Microsoft C runtime `rand` — the engine's only source of randomness,
//! used by [`crate::deal`] and nothing else.
//!
//! The original Windows Solitaire shuffles with the `rand`/`srand` pair its C
//! runtime linked in, and reproducing its deals means reproducing that
//! generator exactly:
//!
//! * `srand(seed)` stores the seed into a 32-bit state. The runtime's
//!   `unsigned int` is 16 bits wide, so only the low 16 bits of the seed ever
//!   reach the state and the high half always starts at zero.
//! * `rand()` steps a linear congruential generator with multiplier `214013`
//!   and increment `2531011`, then returns bits 16..30 of the new state — a
//!   value in `0..=32767`.
//!
//! Together with the documented shuffle in [`crate::deal`], this generator is
//! the determinism contract: the same seed must produce the same deal on
//! every platform, architecture, and version, forever. The committed
//! fixtures under `tests/fixtures/` (independently generated by
//! `generate.py`) lock it. **Never change anything here.**

/// The Microsoft C runtime's linear congruential generator.
pub(crate) struct MsRand {
    state: u32,
}

/// LCG multiplier.
const MULTIPLIER: u32 = 214_013;

/// LCG increment.
const INCREMENT: u32 = 2_531_011;

impl MsRand {
    /// Seeds the generator per `srand(seed)`.
    pub(crate) fn new(seed: u16) -> Self {
        Self {
            state: u32::from(seed),
        }
    }

    /// Advances the generator one step and returns a value in `0..=32767`.
    #[allow(clippy::cast_possible_truncation)] // masked to 15 bits before the cast
    pub(crate) fn next(&mut self) -> u16 {
        self.state = self.state.wrapping_mul(MULTIPLIER).wrapping_add(INCREMENT);
        ((self.state >> 16) & 0x7fff) as u16
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The canonical first outputs of the Microsoft C runtime's `rand()`
    /// after `srand(1)` — the sequence every MSVC program prints when it
    /// forgets to seed. Cross-checked against the independent Python
    /// reference implementation in `tests/fixtures/generate.py`.
    #[test]
    fn stream_matches_the_c_runtime_for_seed_1() {
        let mut rng = MsRand::new(1);
        let outputs: Vec<u16> = (0..8).map(|_| rng.next()).collect();
        assert_eq!(
            outputs,
            [41, 18467, 6334, 26500, 19169, 15724, 11478, 29358]
        );
    }

    /// Cross-checked against the independent Python reference implementation.
    #[test]
    fn stream_matches_reference_for_edge_seeds() {
        let mut zero = MsRand::new(0);
        assert_eq!(zero.next(), 38);
        assert_eq!(zero.next(), 7719);

        let mut max = MsRand::new(0x7fff);
        assert_eq!(max.next(), 8737);
        assert_eq!(max.next(), 10287);
    }

    /// Every output must fit the C runtime's `0..=RAND_MAX` contract, so the
    /// modulo reduction in [`crate::deal`] can never see a wider value.
    #[test]
    fn every_output_is_within_rand_max() {
        let mut rng = MsRand::new(12_345);
        for _ in 0..10_000 {
            assert!(rng.next() <= 0x7fff);
        }
    }

    /// The state is 32 bits wide and wraps; seeding only ever fills the low
    /// half, so two seeds that differ above bit 15 cannot exist.
    #[test]
    fn seeding_uses_the_whole_sixteen_bit_seed() {
        let mut low = MsRand::new(0x0001);
        let mut high = MsRand::new(0x8001);
        assert_ne!(low.next(), high.next());
    }
}
