//! Wires the in-tree, CC0-licensed default theme (`themes/default/`,
//! generated by `themes/default/generate.py`) into `cargo test`, so
//! a regression is caught here immediately rather than only in CI's
//! separate `soltool validate` step — this test is the belt to
//! that suspender.

#![allow(clippy::unwrap_used)]

mod common;

use std::path::{Path, PathBuf};

use sol_theme::{RenderMode, Theme};

/// `themes/default`, resolved from the workspace root
/// (`crates/soltool` is two directories below it) so this works regardless
/// of the directory `cargo test` was invoked from.
fn default_theme_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../themes/default")
}

#[test]
fn the_in_tree_default_theme_validates_green_through_the_real_cli() {
    let theme_dir = default_theme_dir();
    let cwd = tempfile::tempdir().unwrap();

    let output = common::run(cwd.path(), &["validate", theme_dir.to_str().unwrap()]);

    assert_eq!(output.status.code(), Some(0));
    assert!(output.stderr.is_empty());
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.contains("Default"), "{stdout}");
    assert!(stdout.contains("vector"), "{stdout}");
    assert!(stdout.contains("2 backs"), "{stdout}");
    assert!(stdout.contains("3 placeholders"), "{stdout}");
}

#[test]
fn the_in_tree_default_theme_is_vector_with_the_win98_base_size_and_a_two_frame_back() {
    let theme = Theme::load_dir(default_theme_dir()).unwrap();

    assert_eq!(theme.manifest.render_mode, RenderMode::Vector);
    assert_eq!(theme.manifest.base_size.width, 71);
    assert_eq!(theme.manifest.base_size.height, 96);
    assert_eq!(theme.faces().count(), 52);

    let two_frame_backs = theme
        .backs()
        .iter()
        .filter(|(_, back)| back.frame_count == 2)
        .count();
    assert_eq!(two_frame_backs, 1, "expected exactly one 2-frame back");

    // All three placeholder slots, each card-sized like every other asset.
    let placeholders: Vec<&str> = theme.placeholders().entries().map(|(key, _)| key).collect();
    assert_eq!(
        placeholders,
        vec!["empty_pile", "stock_recycle", "stock_blocked"]
    );
    for (key, asset) in theme.placeholders().entries() {
        assert_eq!(asset.size.width, 71, "{key}");
        assert_eq!(asset.size.height, 96, "{key}");
    }
}
