//! Fixture tests locking the deterministic deal, forever.
//!
//! The expected files under `fixtures/` were generated by the independent
//! Python reference implementation `fixtures/generate.py`, which re-derives
//! the documented C runtime generator + five-pass swap shuffle + layout
//! procedure from the original binary rather than from this engine. This
//! test renders the Rust deal in the identical format and compares
//! byte-for-byte. If it ever fails, the deal determinism contract has
//! been broken — fix the engine, never the fixtures.

#![allow(clippy::unwrap_used)]

use std::fmt::Write as _;

use sol_engine::{Card, DrawMode, GameConfig, GameState, ScoringMode, Seed, deal};

const FIXTURES: [(u16, &str); 4] = [
    (0, include_str!("fixtures/seed_0.txt")),
    (1, include_str!("fixtures/seed_1.txt")),
    (42, include_str!("fixtures/seed_42.txt")),
    (Seed::MAX, include_str!("fixtures/seed_32767.txt")),
];

fn cards(list: impl IntoIterator<Item = Card>) -> String {
    let names: Vec<String> = list.into_iter().map(|card| card.to_string()).collect();
    names.join(",")
}

/// Renders a dealt state exactly like `fixtures/generate.py` does: tableau
/// lists bottom-to-top, the stock in draw order (first card drawn first).
fn render(seed_value: u16, state: &GameState) -> String {
    let mut out = format!("seed={seed_value}\n");
    for (index, pile) in state.tableaus().enumerate() {
        let down = cards(pile.face_down().iter().copied());
        let up = cards(pile.face_up().iter().copied());
        let _ = writeln!(out, "tableau{index} down={down} up={up}");
    }
    let draw_order = cards(state.stock().iter().rev().copied());
    let _ = writeln!(out, "stock={draw_order}");
    out
}

#[test]
fn dealt_games_match_the_committed_reference_fixtures() {
    let config = GameConfig {
        draw_mode: DrawMode::One,
        scoring: ScoringMode::Standard,
        timed: false,
    };
    for (seed_value, expected) in FIXTURES {
        let state = deal(Seed::new(seed_value).unwrap(), config);
        let rendered = render(seed_value, &state);
        assert_eq!(rendered, expected, "seed {seed_value} deal diverged");
    }
}
